export const tagTypes = {
  auth: "Auth",
  users: "Users",
  user: "User",
  otp: "Otp",
  notifications: "notifications",
  notification: "notification",
  promotion: "promotion",
  setting: "setting",
  dashboard: "dashboard",
  subscription: "subscription",
  profile: "profile",
  productCategory: "productCategory",
  eventCategory: "eventCategory",
  event: "event",
  eventReport: "eventReport",
  productReport: "productReport",
  profileReport: "profileReport",
  pushNotification: "pushNotification",
  content: "content",
  faqs: "faqs",
};

export const tagTypesList = [
  tagTypes.otp,
  tagTypes.auth,
  tagTypes.users,
  tagTypes.user,
  tagTypes.notifications,
  tagTypes.notification,
  tagTypes.setting,
  tagTypes.promotion,
  tagTypes.dashboard,
  tagTypes.subscription,
  tagTypes.profile,
  tagTypes.productCategory,
  tagTypes.eventCategory,
  tagTypes.event,
  tagTypes.eventReport,
  tagTypes.productReport,
  tagTypes.profileReport,
  tagTypes.pushNotification,
  tagTypes.content,
  tagTypes.faqs
];
